spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
        hibernate:
            format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/employee-management
    username: postgres
    password: postgre
    driverClassName: org.postgresql.Driver